name: Docker Image CI

on:
  push:
    branches: [ "agora*" ]

jobs:

  build:

    runs-on: ubuntu-latest
    env:
      HAVE_DOCKERHUB_SECRET: ${{ secrets.DHUB_TOKEN != '' && secrets.DHUB_USER != '' }}

    steps:
    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v1

    - name: Login to DockerHub
      uses: docker/login-action@v1
      id: login
      # If the user set up those variable, it's upstream or (s)he wants the push to happen
      # Otherwise, it might just be someone pushing to their fork, in which case we still
      # want to build as it's useful to test a release before upstreaming it.
      if: env.HAVE_DOCKERHUB_SECRET
      with:
        username: ${{ secrets.DHUB_USER }}
        password: ${{ secrets.DHUB_TOKEN }}

    - name: 'Build and push'
      uses: docker/build-push-action@v2
      with:
        # Either 'success' or 'skipped'
        push: ${{ steps.login.outcome == 'success' }}
        tags: bosagora/agora-el-node:${{ github.ref_name }}
